### ISSUE TITLE
Establish policy for managing new users and projects

### ISSUE THREAD

**Issue by larsks** [open-infrastructure-labs/ops-issues#1]
Right now we allow anyone to authenticate, and then grant self provisioning capabilities via group membership. Should we manage users and projects via git workflow?

**Comment by larsks** [comment]
Solution discussed on 2021-01-06 call:

- Manage projects (and project membership) via YAML files in repository
- Nobody gets self-provisioning privileges

**Comment by tumido** [comment]
Interesting alternative: Openshift native project templates. By setting "our" project template in `openshift-config` namespace we can modify the what RBAC is set on project creation.

A sample project template, which can be adjusted to our needs:
```yaml
$ oc adm create-bootstrap-project-template -o yaml
apiVersion: template.openshift.io/v1
kind: Template
metadata:
  creationTimestamp: null
  name: project-request
objects:
- apiVersion: project.openshift.io/v1
  kind: Project
  metadata:
    annotations:
      openshift.io/description: ${PROJECT_DESCRIPTION}
      openshift.io/display-name: ${PROJECT_DISPLAYNAME}
      openshift.io/requester: ${PROJECT_REQUESTING_USER}
    creationTimestamp: null
    name: ${PROJECT_NAME}
  spec: {}
  status: {}
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    creationTimestamp: null
    name: admin
    namespace: ${PROJECT_NAME}
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: admin
  subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: User
    name: ${PROJECT_ADMIN_USER}
parameters:
- name: PROJECT_NAME
- name: PROJECT_DISPLAYNAME
- name: PROJECT_DESCRIPTION
- name: PROJECT_ADMIN_USER
- name: PROJECT_REQUESTING_USER
```

Reference:
https://docs.openshift.com/container-platform/4.6/applications/projects/configuring-project-creation.html#modifying-template-for-new-projects_configuring-project-creation

This may be able to set all the permissions we need automatically on every project creation (when created by UI or `oc new-project`). I wonder if Argo CD can `CreateProject` instead of `CreateNamespace` somehow? cc @HumairAK

The other way around is what we outlined in the meeting, which is the fully declarative way - having each `Namespace` and all its `RoleBinidings` defined manually in our repo from where ArgoCD would pick them up and deploy on cluster and namespace scope.
